version: "3.9"
services:
  postgres:
    container_name: test_webapp_postgres
    image: postgres
    env_file:
      - .env
    volumes:
      - ./docker_data/pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 5
  app:
    container_name: test_webapp_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DB_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        npm run build &&
        node dist/app.js
      "